plugins {
    id 'java'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

group = 'org.example'
version = '0.1.0'

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                url = "https://libraries.minecraft.net"
            }
        }
        filter {
            includeGroupAndSubgroups("com.mojang")
        }
    }
}

compileJava {
    options.javaModuleVersion = project.version.toString()
    options.javaModuleMainClass = 'dev.lukebemish.larder.Larder'
}

dependencies {
    compileOnly("org.jspecify:jspecify:1.0.0")
    
    implementation("io.javalin:javalin:6.7.0")
    implementation("org.postgresql:postgresql:42.7.11")
}