plugins {
    id 'java'
    // TODO: centralize
    id 'dev.lukebemish.javac-post-processor' version '0.1.10'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

group = 'org.example'
version = '0.1.0'

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                url = "https://libraries.minecraft.net"
            }
        }
        filter {
            includeGroupAndSubgroups("com.mojang")
        }
    }
}

compileJava {
    options.javaModuleVersion = project.version.toString()
    options.javaModuleMainClass = 'dev.lukebemish.larder.Larder'
}

def dashboardProdDirectory = file("dashboard/dist")
def indicesProdDirectory = file("indices/dist")

tasks.register("npmBuildProd", Exec) {
    executable = file("generate.sh")
    environment("LARDER_ENV", "prod")
    outputs.dirs(dashboardProdDirectory, indicesProdDirectory)
    inputs.files(
        "indices/package-lock.json", "indices/package.json", "indices/postcss.config.mjs",
        "dashboard/package-lock.json", "dashboard/package.json", "dashboard/tsconfig.json", "dashboard/index.html", "dashboard/vite.config.ts"
    )
    inputs.dir("indices/src")
    inputs.dir("dashboard/src")
}

@DisableCachingByDefault(because = "For testing, should not be cached")
abstract class TestDev extends DefaultTask {
    @Inject
    abstract ExecOperations getExecOperations()

    @Inject
    abstract ProjectLayout getLayout()

    @Inject
    abstract JavaToolchainService getToolchains()

    @InputFiles
    abstract ConfigurableFileCollection getClasspath()

    @Input
    abstract Property<JavaLauncher> getJavaLauncher()

    @Inject
    TestDev() {
        javaLauncher.convention(toolchains.launcherFor {
            it.languageVersion = JavaLanguageVersion.of(25)
        })
    }

    @TaskAction
    void run() {
        Process generate = new ProcessBuilder(layout.projectDirectory.file("generate.sh").asFile.absolutePath)
            .inheritIO().directory(layout.projectDirectory.asFile).tap {
            environment()["LARDER_ENV"] = "dev"
        }.start()
        try {
            new ProcessBuilder("docker", "compose", "-f", "docker-compose.dev.yml", "up", "--remove-orphans", "--detach")
                .inheritIO().directory(layout.projectDirectory.asFile).start().waitFor().tap {
                if (it != 0) throw new RuntimeException("Error starting docker: $it")
            }
            try {
                execOperations.javaexec {
                    classpath = this.classpath
                    mainModule = "dev.lukebemish.larder"
                    executable = javaLauncher.get().executablePath
                    environment(
                        LARDER_ENV: "dev",
                        LARDER_DB_HOST: "localhost",
                        LARDER_DB_PORT: "5432",
                        LARDER_DB_NAME: "larder",
                        LARDER_DB_USER: "larder",
                        LARDER_DB_PASSWORD: "larder",

                        LARDER_S3_REGION: "",
                        LARDER_S3_ACCESS_KEY_ID: "minioadmin",
                        LARDER_S3_SECRET_ACCESS_KEY: "minioadmin",
                        LARDER_S3_ENDPOINT: "http://localhost:9000"
                    )
                    workingDir = layout.projectDirectory
                }
            } finally {
                new ProcessBuilder("docker", "compose", "-f", "docker-compose.dev.yml", "down")
                    .inheritIO().directory(layout.projectDirectory.asFile).start().waitFor().tap {
                    if (it != 0) throw new RuntimeException("Error starting docker: $it")
                }
            }
        } finally {
            generate.destroy()
        }
    }
}

tasks.register("testDev", TestDev) {
    classpath.from(sourceSets.main.runtimeClasspath)
    classpath.from("build/devResources")
}

tasks.named("jar", Jar) {
    from(dashboardProdDirectory) {
        into("dev/lukebemish/larder/dashboard")
    }
    from(indicesProdDirectory) {
        into("dev/lukebemish/larder/indices")
    }
}

dependencies {
    compileOnly("org.jspecify:jspecify:1.0.0")

    implementation("io.javalin:javalin:7.2.2")
    implementation("org.postgresql:postgresql:42.7.11")
    implementation("org.slf4j:slf4j-simple:2.0.16")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.21.2")
    implementation("com.fasterxml.uuid:java-uuid-generator:5.2.0")

    annotationProcessor("dev.lukebemish:polymorphic-signatures:0.1.0")
    compileOnly("dev.lukebemish:polymorphic-signatures:0.1.0")
    implementation("dev.lukebemish:polymorphic-signatures:0.1.0") {
        capabilities {
            requireFeature("utilities")
        }
    }
}

tasks.named('compileJava', JavaCompile) {
    javacPostProcessor.plugins.add('dev.lukebemish.polymorphic-signatures')
}
