plugins {
    id 'java-library'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

group = 'dev.lukebemish.larder'
version = '0.1.0'

dependencies {
    compileOnly(libs.jspecify)
    compileOnly(libs.autoservice.annotations)

    annotationProcessor(libs.autoservice.processor)

    implementation(libs.javacpostprocessor)
}
