plugins {
    id 'java-library'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

group = 'dev.lukebemish.larder'
version = '0.1.0'

dependencies {
    compileOnly("org.jspecify:jspecify:1.0.1")
    compileOnly("com.google.auto.service:auto-service-annotations:1.1.1")

    annotationProcessor("com.google.auto.service:auto-service:1.1.1")

    implementation("dev.lukebemish:javac-post-processor:0.1.10")
}
